name: hockey_forecast_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  in_app_review: ^2.0.3
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/onboarding1.png
    - assets/edit.png
    - assets/profilepicture.png
    - assets/el1.png
    - assets/el2.png
    - assets/el3.png
    - assets/el4.png
    - assets/el5.png
    - assets/im1.png
    - assets/home1.png
    - assets/profile.png
    - assets/news.png
    - assets/settings.png
    - assets/home.png
    - assets/profile1.png
    - assets/news1.png
    - assets/settings1.png
    - assets/imageback.png

